### PR TITLE
fix: saudi iban only with digits

### PR DESCRIPTION
**Pull request by PeterNgTr**
This PR aims to fix the Saudi IBAN which is only with digits in account number.

https://www.iban.com/structure

Screen Shot 2021-07-27 at 1 25 50 PM

### CODE REVIEW

**Comment by koblas** [comment]
IBAN Registry Version 88 

Says: `SA2!n2!n18!c` -- which is what's implemented.  While I might agree that in practice it's only digits, the specification allows for other chapters.

image

**Comment by PeterNgTr** [comment]
Hi @koblas any update on this PR? Cause my tests are now replying on this. If this fix is not possible, I would look into another solution.

**Comment by koblas** [comment]
Fundamentally the goal of this library is to follow the SWIFT specification.  Given that the current implantation is consistent with the specification probably not going to accept this PR

**Comment by PeterNgTr** [comment]
Thanks! Then I would find another library then!

**Comment by PeterNgTr** [comment]
Sorry that's our bad. We implemented the wrong validation from our application.

**Pull request closed without merging**
